# Generated by Django 5.2.5 on 2025-09-08 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_bio_alter_user_cover_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover_photo',
            field=models.ImageField(default='profile/default.jpeg', upload_to='profile'),
        ),
    ]
